export const translations = {
    uz: {
        profile: {
            paymentSection: {
                title: "Qoldiqni to'lash",
                payWithAsaka: "Asaka Bank orqali to'lash",
                payWithPayme: "Payme orqali to'lash",
                securePayment: "Xavfsiz to'lov",
                commission: "Komissiyasiz"
            },
            title: "Profil",
            personalInfo: "Shaxsiy ma'lumot",
            orders: "Buyurtmalar",
            payments: "To'lovlar",
            documents: "Shartnoma",
            overview: "Avtomobil haqida",
            contract: "Shartnoma",
            vehicle: "Transport vositasi",
            delivery: "Yetkazib berish",
            paymentSchedule: "To'lov jadvali",
            nextPayment: "Keyingi to'lov",
            remainingMonths: "Qolgan oylar",
            totalCars: "Avtomobillar",
            downloadContract: "Shartnomani yuklash",
            payNow: "Hozir to'lash",
            orderNumber: "Buyurtma raqami",
            contractNumber: "Shartnoma raqami",
            orderDate: "Shartnoma tuzilgan sana",
            dealer: "Diler",
            model: "Model",
            modification: "Modifikatsiya",
            color: "Rang",
            vin: "VIN raqami",
            queueNumber: "Navbat",
            expectedDate: "Kutilayotgan sana",
            price: "Narxi",
            paid: "To'langan",
            remaining: "Qolgan",
            backToList: "Ortga qaytish",
            status: {
                'новый': 'Yangi',
                'в очереди': 'Navbatda',
                'распределено': 'Taqsimlangan',
                'в пути': 'Yoʻlda',
                'у дилера': 'Dilerda',
                'реализован': 'Yetkazib berilgan',
                'бронь': 'Bron qilingan'
            },
            logout: "Chiqish",
            payment: "To'lov",
            paidAmount: "To'langan summa",
            remainingAmount: "Qoldiq summa",
            orderInfo: "Buyurtma ma'lumotlari",
            noOrders: "Buyurtmalar mavjud emas",
            details: "Batafsil",
            vehicleInfo: "Avtomobil haqida",
            contractInfo: "Ma'lumotlar",
            deliveryInfo: "Taxminiy yetkazib berish muddati",
            vehicleSpecs: "Texnik xususiyatlar",
            progress: "To'lov jarayoni",
            totalAmount: "Shartnoma summasi",
            paymentDate: "To'lov sanasi",
            paymentAmount: "To'lov summasi",
            currentPayment: "Joriy to'lov",
            searchPayments: "Sana yoki summa bo'yicha qidirish...",
            noPayments: "To'lovlar topilmadi",
            paymentStatus: {
                paid: "To'langan",
                pending: "Kutilmoqda",
                "partially-paid": "Qisman to'langan",  // Добавлено
                overdue: "Kechikkan",
                future: "Kelgusi to'lov"
            },
            date: "Sana",
            amount: "Toʻlov summasi",
            statuss: "Holati",
            payWithPayme: "Payme orqali to'lash",
            clientTypes: {
                individual: "Jismoniy shaxs",
                entity: "Yuridik shaxs"
            },
            idNumber: "PINFL/STIR",
            selectRegion: "Viloyatni tanlang",
            allRegions: "Barcha viloyatlar",
            region: "Viloyat",
        }
    },
    ru: {
        profile: {
            paymentSection: {
                title: "Оплатить остаток",
                payWithAsaka: "Оплатить через Asaka Bank",
                payWithPayme: "Оплатить через Payme",
                securePayment: "Безопасная оплата",
                commission: "Без комиссии"
            },
            title: "Профиль",
            personalInfo: "Персональные данные",
            orders: "Заказы",
            payments: "Платежи",
            documents: "Договор",
            overview: "Обзор",
            contract: "Договор",
            vehicle: "Автомобиль",
            delivery: "Поставка",
            paymentSchedule: "График платежей",
            nextPayment: "Следующий платеж",
            remainingMonths: "Осталось месяцев",
            totalCars: "Автомобили",
            downloadContract: "Скачать договор",
            payNow: "Оплатить сейчас",
            orderNumber: "Номер заказа",
            contractNumber: "Номер договора",
            orderDate: "Дата",
            dealer: "Дилер",
            model: "Модель",
            modification: "Модификация",
            color: "Цвет",
            vin: "VIN номер",
            queueNumber: "Очередь",
            expectedDate: "Ожидаемая дата",
            price: "Стоимость",
            paid: "Оплачено",
            remaining: "Осталось",
            backToList: "Вернуться к списку",
            status: {
                'новый': 'Новый',
                'в очереди': 'В очереди',
                'распределено': 'Распределено',
                'в пути': 'В пути',
                'у дилера': 'У дилера',
                'реализован': 'Реализован',
                'бронь': 'Забронирован'
            },
            logout: "Выйти",
            payment: "Оплата",
            paidAmount: "Оплаченная сумма",
            remainingAmount: "Оставшаяся сумма",
            orderInfo: "Информация о заказе",
            noOrders: "Заказы отсутствуют",
            details: "Подробнее",
            vehicleInfo: "Информация об автомобиле",
            contractInfo: "Информация о договоре",
            deliveryInfo: "Информация о доставке",
            vehicleSpecs: "Технические характеристики",
            progress: "Прогресс оплаты",
            totalAmount: "Общая сумма",
            paymentDate: "Дата платежа",
            paymentAmount: "Сумма платежа",
            currentPayment: "Текущий платеж",
            searchPayments: "Поиск по дате или сумме...",
            noPayments: "Платежи не найдены",
            paymentStatus: {
                paid: "Оплачено",
                pending: "Ожидает оплаты",
                "partially-paid": "Частично оплачено", 
                overdue: "Просрочено",
                future: "Будущий платеж"
            },
            date: "Дата",
            amount: "Сумма",
            statuss: "Статус",
            payWithPayme: "Оплатить через Payme",
            clientTypes: {
                individual: "Физическое лицо",
                entity: "Юридическое лицо"
            },
            idNumber: "ПИНФЛ/ИНН",
            selectRegion: "Выберите регион",
            allRegions: "Все регионы",
            region: "Регион",
        }
    }
} as const;